In [1]:
import numpy as np
import pandas as pd

**loading the data**

In [2]:
df=pd.read_csv(r'anime.csv')
df

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [3]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [4]:
#make a new column for episode count
df['Title']

0     Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1     Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2     Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3     Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4     Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
5     Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...
6     Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...
7     Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...
8     Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...
9     Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...
10    Shingeki no Kyojin: The Final Season - Kankets...
11    Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
12    Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...
13    Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...
14    Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...
15    GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...
16    Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...
17    3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...
18    Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...
19    Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...
20    Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...
21    Violet Evergarden MovieMovie (1 eps)Sep 2020 -...
22    Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...
23    Gintama.: Shirogane no Tamashii-hen - Kouhan-s...
24    MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...
25    Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...
26    Kaguya-sama wa Kokurasetai: First Kiss wa Owar...
27    Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...
28    The First Slam DunkMovie (1 eps)Dec 2022 - Dec...
29    Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...
30    Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...
31    Gintama.: Shirogane no Tamashii-henTV (12 eps)...
32    Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...
33    Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...
34    Shingeki no Kyojin: The Final SeasonTV (16 eps...
35    Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...
36    Kizumonogatari III: Reiketsu-henMovie (1 eps)J...
37    "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...
38    Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...
39    Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...
40    Monogatari Series: Second SeasonTV (26 eps)Jul...
41    Shingeki no Kyojin: The Final Season Part 2TV ...
42    Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...
43    Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...
44    Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...
45    Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...
46    Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...
47    Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...
48    Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...
49    Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...
Name: Title, dtype: object

In [5]:
def extract_eps(txt):
    check = False
    data = ""
    for i in txt:
        if i == ")":
            check = False
            return data
        if check == True: 
            data = data + i 
        if i == '(':
            check = True

In [6]:
df["Episodes"]=df['Title'].apply(extract_eps)
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps

In [7]:
df["Episodes"]=df["Episodes"].str.replace("eps","")
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10      64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07      24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06      13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06      51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05      10

In [8]:
type(df.loc[0]['Episodes'])

str

In [9]:
df['Episodes']=df['Episodes'].astype(int)
type(df.loc[0]['Episodes'])
df.head()

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

In [10]:
#make a new column for time stamp
df['Title'][0]

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [11]:
# def extraction_time(txt):
#     check = False
#     data = ""
#     for i in range(len(txt)):
#         if txt[i] == ')':
#             for j in range(i+1,i+20):
#                 data += txt[j]

#             return data

def time_count(text):
    ans=""
    for i in range(0,len(text)):
        if text[i]==")":
            for j in range(i+1,i+20):
                ans=ans+text[j]
                
            return(ans)

In [12]:
df['time-stamp']=df["Title"].apply(time_count)
df.head()

,Rank,Title,Score,Episodes,time-stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [13]:
df[['start_date','end_date']]=df['time-stamp'].str.split("-",expand=True) #for splitting values based on -
df.head()

,Rank,Title,Score,Episodes,time-stamp,start_date,end_date
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,Apr 2009,Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,Apr 2011,Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,Oct 2022,Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,Apr 2015,Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,Apr 2019,Jul 2019

In [14]:
df['start_date'] = df['start_date'].str.strip() #strip----> for removing spaces
df['end_date'] = df['end_date'].str.strip()

df['start_date'] = pd.to_datetime(df['start_date'], format='%b %Y')
df['end_date'] = pd.to_datetime(df['end_date'], format='%b %Y')
df.head()

,Rank,Title,Score,Episodes,time-stamp,start_date,end_date
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,2009-04-01,2010-07-01
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,2011-04-01,2011-09-01
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2022-10-01,2022-12-01
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,2015-04-01,2016-03-01
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,2019-04-01,2019-07-01

In [15]:
df['total_months']=(df['end_date'].dt.year - df['start_date'].dt.year)*12 + (df['end_date'].dt.month - df['start_date'].dt.month)+1
df

,Rank,Title,Score,Episodes,time-stamp,start_date,end_date,total_months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,2009-04-01,2010-07-01,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,2011-04-01,2011-09-01,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,2015-04-01,2016-03-01,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,2019-04-01,2019-07-01,4
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012,2011-04-01,2012-03-01,12
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021,2021-01-01,2021-01-01,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,2011-10-01,2014-09-01,36
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022,2022-04-01,2022-06-01,3
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013,2012-10-01,2013-03-01,6
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023,2023-03-01,2023-05-01,3
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,1988-01-01,1997-03-01,111
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023,2023-07-01,2023-08-01,2
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021,2021-04-01,2021-06-01,3
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017,2017-01-01,2017-03-01,3
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,2006-04-01,2010-03-01,48
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016,2016-09-01,2016-09-01,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018,2017-10-01,2018-03-01,6
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009,2008-10-01,2009-03-01,6
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008,2008-04-01,2008-09-01,6
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013,2013-07-01,2013-07-01,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020,2020-09-01,2020-09-01,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017,2017-08-01,2017-08-01,1
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018,2018-07-01,2018-10-01,4
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,2004-04-01,2005-09-01,18
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016,2016-08-01,2016-08-01,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022,2022-12-01,2022-12-01,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,3
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022,2022-12-01,2022-12-01,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023,2023-01-01,2023-06-01,6
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023,2023-07-01,2023-08-01,2
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018,2018-01-01,2018-03-01,3
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021,2020-04-01,2021-10-01,19
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019,2019-01-01,2019-04-01,4
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021,2020-12-01,2021-03-01,4
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022,2021-12-01,2022-02-01,3
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017,2017-01-01,2017-01-01,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023,2023-04-01,2023-06-01,3
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016,2016-10-01,2016-12-01,3
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001,2001-07-01,2001-07-01,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013,2013-07-01,2013-12-01,6
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022,2022-01-01,2022-04-01,4
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,2000-10-01,2002-03-01,18
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999,1998-04-01,1999-04-01,13
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022,2022-04-01,2022-10-01,7
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019,2019-07-01,2019-12-01,6
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014,2014-10-01,2014-12-01,3
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017,2017-01-01,2017-03-01,3
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,3
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999,1999-02-01,1999-09-01,8

In [16]:
#which anime has the highest score
highest_score=df['Score'].max()
highest_score

9.1

In [17]:
df[df['Score'] == df['Score'].max()]
df[df['Score']==df['Score'].max()]['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: object

In [18]:
#give me top 5 highest scoring anime
df.head()

,Rank,Title,Score,Episodes,time-stamp,start_date,end_date,total_months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,2009-04-01,2010-07-01,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,2011-04-01,2011-09-01,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,2015-04-01,2016-03-01,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,2019-04-01,2019-07-01,4

In [19]:
#which anime has the highest episode count
highest_eps=df['Episodes'].max()
highest_eps

201

In [20]:
#animes with top 5 episode count
topFive=df['Episodes'].head()
topFive

0    64
1    24
2    13
3    51
4    10
Name: Episodes, dtype: int64

In [21]:
#which is the longest running anime
longest=df['total_months'].max()
longest

111