In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame({
"City":["Delhi","Delhi","Delhi","Mumbai","Mumbai","Mumbai"],
"Product":["Shoes","Shoes","Watch","Shoes","Watch","Watch"],
"Sales":[200,150,300,400,250,300]
})

In [3]:
df.pivot_table(values="Sales", index="City", columns="Product", aggfunc="sum",fill_value=0)

Product  Shoes  Watch
City
Delhi      350    300
Mumbai     400    550

In [4]:
data = pd.DataFrame({
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
})
data

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    991     43   John
1  2023-01-02       B   West    556     36   Mary
2  2023-01-03       C  North    595     21    Bob
3  2023-01-04       D  South    285     38  Alice
4  2023-01-05       A   East    411     86   John
5  2023-01-06       B   West    396     14   Mary
6  2023-01-07       C  North    821     13    Bob
7  2023-01-08       D  South    250     35  Alice
8  2023-01-09       A   East    652     33   John
9  2023-01-10       B   West    391     38   Mary
10 2023-01-11       C  North    130     79    Bob
11 2023-01-12       D  South    478     44  Alice
12 2023-01-13       A   East    747     42   John
13 2023-01-14       B   West    923     92   Mary
14 2023-01-15       C  North    275     39    Bob
15 2023-01-16       D  South    479     44  Alice
16 2023-01-17       A   East    966     68   John
17 2023-01-18       B   West    648     31   Mary
18 2023-01-19       C  North    410     60    Bob
19 2023-01-20       D  South    727     20  Alice

In [5]:
data["Month"]=data['Date'].dt.month_name()
data

         Date Product Region  Sales  Units    Rep    Month
0  2023-01-01       A   East    991     43   John  January
1  2023-01-02       B   West    556     36   Mary  January
2  2023-01-03       C  North    595     21    Bob  January
3  2023-01-04       D  South    285     38  Alice  January
4  2023-01-05       A   East    411     86   John  January
5  2023-01-06       B   West    396     14   Mary  January
6  2023-01-07       C  North    821     13    Bob  January
7  2023-01-08       D  South    250     35  Alice  January
8  2023-01-09       A   East    652     33   John  January
9  2023-01-10       B   West    391     38   Mary  January
10 2023-01-11       C  North    130     79    Bob  January
11 2023-01-12       D  South    478     44  Alice  January
12 2023-01-13       A   East    747     42   John  January
13 2023-01-14       B   West    923     92   Mary  January
14 2023-01-15       C  North    275     39    Bob  January
15 2023-01-16       D  South    479     44  Alice  January
16 2023-01-17       A   East    966     68   John  January
17 2023-01-18       B   West    648     31   Mary  January
18 2023-01-19       C  North    410     60    Bob  January
19 2023-01-20       D  South    727     20  Alice  January

In [6]:
data['Month']=data['Date'].dt.month
data

         Date Product Region  Sales  Units    Rep  Month
0  2023-01-01       A   East    991     43   John      1
1  2023-01-02       B   West    556     36   Mary      1
2  2023-01-03       C  North    595     21    Bob      1
3  2023-01-04       D  South    285     38  Alice      1
4  2023-01-05       A   East    411     86   John      1
5  2023-01-06       B   West    396     14   Mary      1
6  2023-01-07       C  North    821     13    Bob      1
7  2023-01-08       D  South    250     35  Alice      1
8  2023-01-09       A   East    652     33   John      1
9  2023-01-10       B   West    391     38   Mary      1
10 2023-01-11       C  North    130     79    Bob      1
11 2023-01-12       D  South    478     44  Alice      1
12 2023-01-13       A   East    747     42   John      1
13 2023-01-14       B   West    923     92   Mary      1
14 2023-01-15       C  North    275     39    Bob      1
15 2023-01-16       D  South    479     44  Alice      1
16 2023-01-17       A   East    966     68   John      1
17 2023-01-18       B   West    648     31   Mary      1
18 2023-01-19       C  North    410     60    Bob      1
19 2023-01-20       D  South    727     20  Alice      1

In [7]:
#data["Quater"]=data["Date"].dt.quarter
data["Quater"]='Q'+ data['Date'].dt.quarter.astype(str)
data

         Date Product Region  Sales  Units    Rep  Month Quater
0  2023-01-01       A   East    991     43   John      1     Q1
1  2023-01-02       B   West    556     36   Mary      1     Q1
2  2023-01-03       C  North    595     21    Bob      1     Q1
3  2023-01-04       D  South    285     38  Alice      1     Q1
4  2023-01-05       A   East    411     86   John      1     Q1
5  2023-01-06       B   West    396     14   Mary      1     Q1
6  2023-01-07       C  North    821     13    Bob      1     Q1
7  2023-01-08       D  South    250     35  Alice      1     Q1
8  2023-01-09       A   East    652     33   John      1     Q1
9  2023-01-10       B   West    391     38   Mary      1     Q1
10 2023-01-11       C  North    130     79    Bob      1     Q1
11 2023-01-12       D  South    478     44  Alice      1     Q1
12 2023-01-13       A   East    747     42   John      1     Q1
13 2023-01-14       B   West    923     92   Mary      1     Q1
14 2023-01-15       C  North    275     39    Bob      1     Q1
15 2023-01-16       D  South    479     44  Alice      1     Q1
16 2023-01-17       A   East    966     68   John      1     Q1
17 2023-01-18       B   West    648     31   Mary      1     Q1
18 2023-01-19       C  North    410     60    Bob      1     Q1
19 2023-01-20       D  South    727     20  Alice      1     Q1

In [8]:
#Sale of products in each region
pd.pivot_table(data,values='Sales',index="Region",columns='Product',aggfunc='mean')

Product      A      B      C      D
Region
East     753.4    NaN    NaN    NaN
North      NaN    NaN  446.2    NaN
South      NaN    NaN    NaN  443.8
West       NaN  582.8    NaN    NaN

In [9]:
data

         Date Product Region  Sales  Units    Rep  Month Quater
0  2023-01-01       A   East    991     43   John      1     Q1
1  2023-01-02       B   West    556     36   Mary      1     Q1
2  2023-01-03       C  North    595     21    Bob      1     Q1
3  2023-01-04       D  South    285     38  Alice      1     Q1
4  2023-01-05       A   East    411     86   John      1     Q1
5  2023-01-06       B   West    396     14   Mary      1     Q1
6  2023-01-07       C  North    821     13    Bob      1     Q1
7  2023-01-08       D  South    250     35  Alice      1     Q1
8  2023-01-09       A   East    652     33   John      1     Q1
9  2023-01-10       B   West    391     38   Mary      1     Q1
10 2023-01-11       C  North    130     79    Bob      1     Q1
11 2023-01-12       D  South    478     44  Alice      1     Q1
12 2023-01-13       A   East    747     42   John      1     Q1
13 2023-01-14       B   West    923     92   Mary      1     Q1
14 2023-01-15       C  North    275     39    Bob      1     Q1
15 2023-01-16       D  South    479     44  Alice      1     Q1
16 2023-01-17       A   East    966     68   John      1     Q1
17 2023-01-18       B   West    648     31   Mary      1     Q1
18 2023-01-19       C  North    410     60    Bob      1     Q1
19 2023-01-20       D  South    727     20  Alice      1     Q1

In [10]:
pd.pivot_table(data,values=["Sales","Units"],index="Product",columns="Region",aggfunc="median")

         Sales                      Units
Region    East  North  South   West  East North South  West
Product
A        747.0    NaN    NaN    NaN  43.0   NaN   NaN   NaN
B          NaN    NaN    NaN  556.0   NaN   NaN   NaN  36.0
C          NaN  410.0    NaN    NaN   NaN  39.0   NaN   NaN
D          NaN    NaN  478.0    NaN   NaN   NaN  38.0   NaN

In [17]:
pd.crosstab(data['Product'],data["Region"])

Region   East  North  South  West
Product
A           5      0      0     0
B           0      0      0     5
C           0      5      0     0
D           0      0      5     0

In [21]:
data2=pd.crosstab(data["Region"],data["Product"],values=data["Sales"],aggfunc="sum")
data2

Product       A       B       C       D
Region
East     3767.0     NaN     NaN     NaN
North       NaN     NaN  2231.0     NaN
South       NaN     NaN     NaN  2219.0
West        NaN  2914.0     NaN     NaN

In [16]:
data2.stack()

Region  Product
East    A          3767.0
North   C          2231.0
South   D          2219.0
West    B          2914.0
dtype: float64